package top.egon.cola.component.yuheng.admin.mcp.converter;

import java.util.List;
import lombok.extern.slf4j.Slf4j;
import org.mapstruct.BeanMapping;
import org.mapstruct.Builder;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.factory.Mappers;
import org.springframework.stereotype.Component;
import top.egon.cola.component.common.core.converter.BaseConverter;
import top.egon.cola.component.yuheng.admin.mcp.domain.bo.McpApprovalBO;
import top.egon.cola.component.yuheng.admin.mcp.domain.po.McpApprovalRecordPO;

/**
 * 中文说明：{@code McpApprovalPersistenceConverter} 是 {@code gateway_mcp_approval} 在持久边界唯一的 MapStruct 转换器，负责
 * {@link McpApprovalRecordPO} 行模型与 {@link McpApprovalBO} 业务载体之间的双向映射：端口上的审批令牌标识落在协议列
 * {@code approval_key}（技术 {@code id} 由边界生成，写方向绝不触碰），MCP 主体租户落在 {@code subject_tenant_id}
 * （MP 的 {@code tenant_id} 是管理面上下文租户）；业务载体按原语义只承载令牌的八项身份事实与签发/到期区间，
 * 因此 {@code status}、业务 {@code revision} 与 {@code consumed_at} 三列在写方向被显式忽略，由门面按被替换 SQL 里的字面量
 * （{@code 'PENDING'}、{@code 0}、{@code NULL}）逐列补齐，读方向也只投影载体声明的字段；本表没有 jsonb 列，
 * 故此处不做任何编解码。
 * English summary: {@code McpApprovalPersistenceConverter} is the only MapStruct converter at the persistence boundary of
 * {@code gateway_mcp_approval}, mapping {@link McpApprovalRecordPO} rows and {@link McpApprovalBO} carriers both ways: the
 * protocol approval identifier lands in {@code approval_key} (the technical {@code id} is generated by the guarded boundary
 * and never written from this side) and the MCP subject tenant lands in {@code subject_tenant_id} (the MP {@code tenant_id}
 * is the management-plane context tenant). Because the business carrier keeps exactly the eight identity facts and the
 * issue/expiry window of the replaced carrier, {@code status}, the business {@code revision} and {@code consumed_at} are
 * ignored explicitly on the write side and filled column by column by the facade with the literals of the replaced SQL
 * ({@code 'PENDING'}, {@code 0}, {@code NULL}); this table has no jsonb column, so no codec happens here.
 *
 * 用法 / Usage: 由 {@code gateway_mcp_approval} 的受守卫 MP 门面注入（bean 名 {@code mcpApprovalPersistenceConverter}）；
 * 写方向不触碰租户、审计、软删、版本与技术主键，因为它们由 {@code EgonColaMetaObjectHandler} 与 {@code ASSIGN_ID} 独占，
 * 业务 CAS 列 {@code revision} 与 MP {@code version} 互不替代。
 * Injected by the guarded {@code gateway_mcp_approval} facade under the bean name {@code mcpApprovalPersistenceConverter};
 * the write direction never touches the tenant, audit, soft-delete, version or technical identifier columns because
 * {@code EgonColaMetaObjectHandler} and {@code ASSIGN_ID} own them, while the business CAS column {@code revision} stays
 * independent of the MP {@code version}.
 */
@Slf4j
@Component("mcpApprovalPersistenceConverter")
public class McpApprovalPersistenceConverter implements BaseConverter<
        McpApprovalRecordPO,
        McpApprovalBO> {

    /**
     * 中文说明：表示 MapStruct 生成的同包结构映射器实例，本类只做空值守护与日志边界。
     * English summary: The MapStruct generated same-package structural mapper; this class only adds null guarding and logging.
     *
     * 用法 / Usage: 仅由本转换器的公开方法调用。/ Invoked only by the public methods of this converter.
     */
    private static final McpApprovalMapping MAPPING =
            Mappers.getMapper(McpApprovalMapping.class);

    /**
     * 中文说明：执行 toPersistence 操作，把审批载体渲染为 MP 行模型；状态、修订与消费时刻留空，由门面按旧 SQL 字面量补齐。
     * English summary: Executes the toPersistence operation, rendering an approval carrier into the MyBatis-Plus row model;
     * status, revision and the consumption instant stay empty for the facade to fill with the legacy literals.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpApprovalPersistenceConverter.toPersistence(approvalBO)}。传入 {@code null} 返回 {@code null}。
     * Passing {@code null} returns {@code null}.
     * @param carrier 参数 业务载体；parameter business carrier。
     * @return 返回 行模型；returns the row model.
     */
    public McpApprovalRecordPO toPersistence(McpApprovalBO carrier) {
        if (carrier == null) {
            log.debug("gateway_mcp_approval business carrier is absent; no row rendered");
            return null;
        }
        return MAPPING.toRow(carrier);
    }

    /**
     * 中文说明：执行 toBusiness 操作，把审批行投影为业务载体（仅载体声明的身份与时间区间字段）。
     * English summary: Executes the toBusiness operation, projecting an approval row onto the business carrier (only the
     * identity and validity-window fields the carrier declares).
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpApprovalPersistenceConverter.toBusiness(row)}。传入 {@code null} 返回 {@code null}。
     * Passing {@code null} returns {@code null}.
     * @param row 参数 行模型；parameter row model。
     * @return 返回 业务载体；returns the business carrier.
     */
    public McpApprovalBO toBusiness(McpApprovalRecordPO row) {
        if (row == null) {
            log.debug("gateway_mcp_approval row is absent; no business carrier projected");
            return null;
        }
        return MAPPING.toBusiness(row);
    }

    /**
     * 中文说明：执行 toPersistenceList 操作，按列表顺序渲染审批载体。
     * English summary: Executes the toPersistenceList operation, rendering every approval carrier in order; null or empty input
     * yields an empty list and never {@code null}.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpApprovalPersistenceConverter.toPersistenceList(carriers)}。
     * @param carriers 参数 业务载体列表；parameter business carriers.
     * @return 返回 行模型列表；returns the row models.
     */
    public List<McpApprovalRecordPO> toPersistenceList(List<McpApprovalBO> carriers) {
        return toSourceList(carriers);
    }

    /**
     * 中文说明：执行 toBusinessList 操作，按列表顺序投影审批行。
     * English summary: Executes the toBusinessList operation, projecting every approval row in order; null or empty input
     * yields an empty list and never {@code null}.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpApprovalPersistenceConverter.toBusinessList(rows)}。
     * @param rows 参数 行模型列表；parameter row models.
     * @return 返回 业务载体列表；returns the business carriers.
     */
    public List<McpApprovalBO> toBusinessList(List<McpApprovalRecordPO> rows) {
        return toTargetList(rows);
    }

    /**
     * 中文说明：执行 toTarget 操作，即 {@code BaseConverter} 的正向投影（行模型 -> 业务载体）。
     * English summary: Executes the toTarget operation, the forward projection of {@code BaseConverter} (row model to business
     * carrier).
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpApprovalPersistenceConverter.toTarget(row)}。
     * @param source 参数 行模型；parameter row model。
     * @return 返回 业务载体；returns the business carrier.
     */
    @Override
    public McpApprovalBO toTarget(McpApprovalRecordPO source) {
        return toBusiness(source);
    }

    /**
     * 中文说明：执行 toSource 操作，即 {@code BaseConverter} 的反向渲染（业务载体 -> 行模型）。
     * English summary: Executes the toSource operation, the reverse rendering of {@code BaseConverter} (business carrier to row
     * model).
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpApprovalPersistenceConverter.toSource(carrier)}。
     * @param target 参数 业务载体；parameter business carrier。
     * @return 返回 行模型；returns the row model.
     */
    @Override
    public McpApprovalRecordPO toSource(McpApprovalBO target) {
        return toPersistence(target);
    }

    /**
     * 中文说明：执行 newRow 操作，是 {@code toPersistence} 的插入别名，语义为「只带身份与有效期业务列的新行」，
     * 技术主键、租户、审计、软删、版本以及状态机列一律留空交由受守卫边界与门面补齐。
     * English summary: Executes the newRow operation, an insert alias of {@code toPersistence} producing a row carrying only the
     * identity and validity business columns; the technical identifier, tenant, audit, soft-delete and version columns plus
     * the state-machine columns stay empty for the guarded boundary and the facade to fill.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpApprovalPersistenceConverter.newRow(approvalBO)}。
     * @param carrier 参数 业务载体；parameter business carrier。
     * @return 返回 待插入行模型；returns the row model to insert.
     */
    public McpApprovalRecordPO newRow(McpApprovalBO carrier) {
        return toPersistence(carrier);
    }
}

/**
 * 中文说明：{@code McpApprovalMapping} 是 {@code gateway_mcp_approval} 的 MapStruct 结构映射契约，逐列复刻被替换的手写 JDBC
 * 语义：{@code approval_key} 与 {@code subject_tenant_id} 承载端口编号与 MCP 主体租户，令牌摘要与参数摘要按
 * {@code varchar(64)} 原样透传（长度校验由业务载体的摘要守护与数据库 CHECK 共同负责），状态、修订与消费时刻
 * 属于状态机列，写方向显式忽略以免用业务载体伪造生命周期事实；受保护技术列全部忽略，因为
 * {@code EgonColaMetaObjectHandler} 独占租户、审计、软删与 MP 版本列；{@code unmappedTargetPolicy=ERROR}
 * 保证任何新增列都必须在此显式表态。
 * English summary: {@code McpApprovalMapping} is the MapStruct structural contract for {@code gateway_mcp_approval}, mirroring
 * the hand-written JDBC it replaces column by column: {@code approval_key} and {@code subject_tenant_id} carry the port
 * identifier and the MCP subject tenant, the token and argument digests pass through as {@code varchar(64)} text (their
 * length rules stay shared by the carrier's digest guard and the database CHECKs), and status, revision and the consumption
 * instant are state-machine columns ignored on the write side so a business carrier can never fabricate lifecycle facts;
 * every protected technical column stays ignored because {@code EgonColaMetaObjectHandler} owns the tenant, audit,
 * soft-delete and MP version columns; {@code unmappedTargetPolicy=ERROR} forces every new column to be stated explicitly here.
 *
 * 用法 / Usage: 由 {@link McpApprovalPersistenceConverter} 通过 {@code Mappers} 持有，不对外暴露，也不登记为 Spring bean。
 * Held by {@link McpApprovalPersistenceConverter} through {@code Mappers}; neither published to callers nor registered as a
 * bean.
 */
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
interface McpApprovalMapping {

    /**
     * 中文说明：执行 toBusiness 操作，按 {@code McpApprovalBO} 的字段顺序投影审批行。
     * English summary: Executes the toBusiness operation, projecting an approval row onto {@code McpApprovalBO}.
     *
     * 用法 / Usage: 仅由 {@link McpApprovalPersistenceConverter#toBusiness(McpApprovalRecordPO)} 调用。
     * @param source 参数 行模型；parameter row model。
     * @return 返回 业务载体；returns the business carrier.
     */
    @BeanMapping(builder = @Builder(disableBuilder = true))
    @Mapping(target = "id", source = "approvalKey")
    @Mapping(target = "tokenDigest", source = "tokenDigest")
    @Mapping(target = "subjectId", source = "subjectId")
    @Mapping(target = "tenantId", source = "subjectTenantId")
    @Mapping(target = "clientId", source = "clientId")
    @Mapping(target = "serverCode", source = "serverCode")
    @Mapping(target = "toolName", source = "toolName")
    @Mapping(target = "argumentDigest", source = "argumentDigest")
    @Mapping(target = "issuedAt", source = "issuedAt")
    @Mapping(target = "expiresAt", source = "expiresAt")
    McpApprovalBO toBusiness(McpApprovalRecordPO source);

    /**
     * 中文说明：执行 toRow 操作，把审批载体写回行模型；技术主键留空由 {@code ASSIGN_ID} 生成，端口编号写进协议列
     * {@code approval_key}，主体租户写进 {@code subject_tenant_id}，状态机三列与受保护技术列一律忽略。
     * English summary: Executes the toRow operation, writing the approval carrier back onto the row model; the technical primary
     * key stays empty for {@code ASSIGN_ID}, the port identifier is written into the protocol column {@code approval_key},
     * the subject tenant into {@code subject_tenant_id}, and the three state-machine columns plus every protected technical
     * column stay ignored.
     *
     * 用法 / Usage: 仅由 {@link McpApprovalPersistenceConverter#toPersistence(McpApprovalBO)} 调用。
     * @param source 参数 业务载体；parameter business carrier。
     * @return 返回 行模型；returns the row model.
     */
    @BeanMapping(builder = @Builder(disableBuilder = true))
    @Mapping(target = "approvalKey", source = "id")
    @Mapping(target = "subjectTenantId", source = "tenantId")
    @Mapping(target = "tokenDigest", source = "tokenDigest")
    @Mapping(target = "subjectId", source = "subjectId")
    @Mapping(target = "clientId", source = "clientId")
    @Mapping(target = "serverCode", source = "serverCode")
    @Mapping(target = "toolName", source = "toolName")
    @Mapping(target = "argumentDigest", source = "argumentDigest")
    @Mapping(target = "issuedAt", source = "issuedAt")
    @Mapping(target = "expiresAt", source = "expiresAt")
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "revision", ignore = true)
    @Mapping(target = "consumedAt", ignore = true)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "tenantId", ignore = true)
    @Mapping(target = "createUserId", ignore = true)
    @Mapping(target = "createTime", ignore = true)
    @Mapping(target = "updateUserId", ignore = true)
    @Mapping(target = "updateTime", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "version", ignore = true)
    McpApprovalRecordPO toRow(McpApprovalBO source);
}
