package top.egon.cola.component.yuheng.admin.mcp.converter;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;
import java.util.Set;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.mapstruct.BeanMapping;
import org.mapstruct.Builder;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.factory.Mappers;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;
import top.egon.cola.component.common.core.converter.BaseConverter;
import top.egon.cola.component.yuheng.admin.mcp.domain.bo.McpManagedToolOverrideBO;
import top.egon.cola.component.yuheng.admin.mcp.domain.po.McpManagedToolOverrideRecordPO;

/**
 * 中文说明：{@code McpManagedToolOverridePersistenceConverter} 是 {@code gateway_mcp_managed_tool_override} 在持久边界唯一的
 * MapStruct 转换器，负责 {@link McpManagedToolOverrideRecordPO} 行模型与 {@link McpManagedToolOverrideBO} 业务载体之间的双向映射：
 * 端口仍沿用 {@code varchar(64)} 的协议主键 {@code tool_id}（技术 {@code id} 由受守卫边界生成，写方向绝不触碰），而
 * {@code gateway_group_id}/{@code operation_id}/{@code server_id} 在新模型下是 {@code bigint} 外键，故按十进制文本双向换算
 * （空白按「未指向任何资源」读作 {@code null}，非法文本按调用方契约错误拒绝而不是写出 {@code null} 冒充链接成功）；
 * {@code additional_permissions} 是 {@code NOT NULL} 的 jsonb 数组列，经 Spring 托管的 Jackson 在 {@code JsonNode} 与
 * {@code Set<String>} 之间往返，编解码只在本类完成（映射接口不持有裸序列化器），解码失败沿用原
 * 「stored MCP string set is invalid」文案；业务 {@code revision} 的可空列按原 {@code getLong} 读作 0，与 MP 的
 * {@code version} 互不替代。
 * English summary: {@code McpManagedToolOverridePersistenceConverter} is the only MapStruct converter at the persistence boundary of
 * {@code gateway_mcp_managed_tool_override}, mapping {@link McpManagedToolOverrideRecordPO} rows and
 * {@link McpManagedToolOverrideBO} carriers both ways: the port keeps using the {@code varchar(64)} protocol key {@code tool_id}
 * (the technical {@code id} is generated by the guarded boundary and never written from this side) while
 * {@code gateway_group_id}/{@code operation_id}/{@code server_id} became {@code bigint} foreign keys, so they are converted through
 * decimal text in both directions (blank reads as {@code null}, i.e. no linked resource, and malformed text is rejected as a caller
 * contract error instead of writing {@code null} and pretending the link succeeded); {@code additional_permissions} is a
 * {@code NOT NULL} jsonb array column that round-trips through the Spring-managed Jackson mapper between a {@code JsonNode} and a
 * {@code Set<String>}, encoded and decoded only in this class (the mapping interface holds no raw serializer), and a decoding failure
 * keeps the legacy {@code stored MCP string set is invalid} message; a null business {@code revision} reads as 0 exactly like the
 * legacy {@code getLong}, staying independent of the MP {@code version}.
 *
 * 用法 / Usage: 由 {@code gateway_mcp_managed_tool_override} 的受守卫 MP 门面注入（bean 名
 * {@code mcpManagedToolOverridePersistenceConverter}）；写方向不触碰租户、审计、软删、版本与技术主键，因为它们由
 * {@code EgonColaMetaObjectHandler} 与 {@code ASSIGN_ID} 独占。门面单独回写权限数组时调用
 * {@link #permissionsNode(Set)}。
 * Injected by the guarded {@code gateway_mcp_managed_tool_override} facade under the bean name
 * {@code mcpManagedToolOverridePersistenceConverter}; the write direction never touches the tenant, audit, soft-delete, version or
 * technical identifier columns because {@code EgonColaMetaObjectHandler} and {@code ASSIGN_ID} own them. A facade rewriting only the
 * permission array calls {@link #permissionsNode(Set)}.
 */
@Slf4j
@Component("mcpManagedToolOverridePersistenceConverter")
@RequiredArgsConstructor
public class McpManagedToolOverridePersistenceConverter implements BaseConverter<
        McpManagedToolOverrideRecordPO,
        McpManagedToolOverrideBO> {

    /**
     * 中文说明：表示 MapStruct 生成的同包结构映射器实例，本类只补充 jsonb 编解码、空值守护与日志边界。
     * English summary: The MapStruct generated same-package structural mapper; this class only adds jsonb codec, null guarding and
     * logging.
     *
     * 用法 / Usage: 仅由本转换器的公开方法调用。/ Invoked only by the public methods of this converter.
     */
    private static final McpManagedToolOverrideMapping MAPPING =
            Mappers.getMapper(McpManagedToolOverrideMapping.class);

    /**
     * 中文说明：表示 STRING_SET 这一固定值，声明 {@code additional_permissions} 列的字符串集合载体类型，与原持久化边界的
     * {@code Set<String>} 读型一致。
     * English summary: Represents the fixed string set value, the structured carrier type of the {@code additional_permissions} column,
     * identical to the {@code Set<String>} read type of the replaced persistence boundary.
     *
     * 用法 / Usage: 仅由本类的权限数组解码使用。/ Used only by the permission-array decoding of this class.
     */
    private static final TypeReference<Set<String>> STRING_SET =
            new TypeReference<>() {
            };

    @Qualifier("jacksonObjectMapper")
    private final ObjectMapper objectMapper;

    /**
     * 中文说明：执行 toPersistence 操作，把受管工具覆盖载体渲染为 MP 行模型，并编码 jsonb 权限数组列。
     * English summary: Executes the toPersistence operation, rendering a managed Tool override carrier into the MyBatis-Plus row model
     * and encoding the jsonb permission-array column.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpManagedToolOverridePersistenceConverter.toPersistence(overrideBO)}。传入 {@code null}
     * 返回 {@code null}。Passing {@code null} returns {@code null}.
     * @param carrier 参数 业务载体；parameter business carrier。
     * @return 返回 行模型；returns the row model.
     */
    public McpManagedToolOverrideRecordPO toPersistence(McpManagedToolOverrideBO carrier) {
        if (carrier == null) {
            log.debug("gateway_mcp_managed_tool_override business carrier is absent; no row rendered");
            return null;
        }
        McpManagedToolOverrideRecordPO row = MAPPING.toRow(carrier);
        row.setAdditionalPermissions(permissionsNode(carrier.getAdditionalPermissions()));
        return row;
    }

    /**
     * 中文说明：执行 toBusiness 操作，把受管工具覆盖行投影为业务载体，解码 jsonb 权限数组列。
     * English summary: Executes the toBusiness operation, projecting an override row onto the business carrier and decoding the jsonb
     * permission-array column.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpManagedToolOverridePersistenceConverter.toBusiness(row)}。传入 {@code null}
     * 返回 {@code null}。Passing {@code null} returns {@code null}.
     * @param row 参数 行模型；parameter row model。
     * @return 返回 业务载体；returns the business carrier.
     */
    public McpManagedToolOverrideBO toBusiness(McpManagedToolOverrideRecordPO row) {
        if (row == null) {
            log.debug("gateway_mcp_managed_tool_override row is absent; no business carrier projected");
            return null;
        }
        McpManagedToolOverrideBO carrier = MAPPING.toBusiness(row);
        carrier.setAdditionalPermissions(stringSet(row.getAdditionalPermissions()));
        return carrier;
    }

    /**
     * 中文说明：执行 toPersistenceList 操作，按列表顺序渲染受管工具覆盖载体。
     * English summary: Executes the toPersistenceList operation, rendering every override carrier in order; null or empty input yields
     * an empty list and never {@code null}.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpManagedToolOverridePersistenceConverter.toPersistenceList(carriers)}。
     * @param carriers 参数 业务载体列表；parameter business carriers.
     * @return 返回 行模型列表；returns the row models.
     */
    public List<McpManagedToolOverrideRecordPO> toPersistenceList(
            List<McpManagedToolOverrideBO> carriers) {
        return toSourceList(carriers);
    }

    /**
     * 中文说明：执行 toBusinessList 操作，按列表顺序投影受管工具覆盖行。
     * English summary: Executes the toBusinessList operation, projecting every override row in order; null or empty input yields an
     * empty list and never {@code null}.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpManagedToolOverridePersistenceConverter.toBusinessList(rows)}。
     * @param rows 参数 行模型列表；parameter row models.
     * @return 返回 业务载体列表；returns the business carriers.
     */
    public List<McpManagedToolOverrideBO> toBusinessList(
            List<McpManagedToolOverrideRecordPO> rows) {
        return toTargetList(rows);
    }

    /**
     * 中文说明：执行 toTarget 操作，即 {@code BaseConverter} 的正向投影（行模型 -> 业务载体）。
     * English summary: Executes the toTarget operation, the forward projection of {@code BaseConverter} (row model to business
     * carrier).
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpManagedToolOverridePersistenceConverter.toTarget(row)}。
     * @param source 参数 行模型；parameter row model。
     * @return 返回 业务载体；returns the business carrier.
     */
    @Override
    public McpManagedToolOverrideBO toTarget(McpManagedToolOverrideRecordPO source) {
        return toBusiness(source);
    }

    /**
     * 中文说明：执行 toSource 操作，即 {@code BaseConverter} 的反向渲染（业务载体 -> 行模型）。
     * English summary: Executes the toSource operation, the reverse rendering of {@code BaseConverter} (business carrier to row
     * model).
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpManagedToolOverridePersistenceConverter.toSource(carrier)}。
     * @param target 参数 业务载体；parameter business carrier。
     * @return 返回 行模型；returns the row model.
     */
    @Override
    public McpManagedToolOverrideRecordPO toSource(McpManagedToolOverrideBO target) {
        return toPersistence(target);
    }

    /**
     * 中文说明：执行 newRow 操作，是 {@code toPersistence} 的插入别名，语义为「只带业务列的新行」，
     * 技术主键、租户、审计、软删与版本列一律留空交由受守卫边界补齐。
     * English summary: Executes the newRow operation, an insert alias of {@code toPersistence} producing a row carrying business
     * columns only; the technical identifier and the tenant, audit, soft-delete and version columns stay empty for the guarded
     * boundary to fill.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpManagedToolOverridePersistenceConverter.newRow(overrideBO)}。
     * @param carrier 参数 业务载体；parameter business carrier。
     * @return 返回 待插入行模型；returns the row model to insert.
     */
    public McpManagedToolOverrideRecordPO newRow(McpManagedToolOverrideBO carrier) {
        return toPersistence(carrier);
    }

    /**
     * 中文说明：执行 permissionsNode 操作，把附加权限集合编码为 jsonb 数组列值；{@code null} 如实返回 {@code null}
     * （该列 {@code NOT NULL}，由数据库拒绝而不是伪造空数组），编码失败沿用原「MCP persistence value cannot be serialized」文案。
     * English summary: Executes the permissionsNode operation, encoding the additional-permission set into the jsonb array column
     * value; {@code null} truthfully yields {@code null} (the column is {@code NOT NULL}, so the database rejects it instead of a
     * fabricated empty array) and an encoding failure keeps the legacy
     * {@code MCP persistence value cannot be serialized} message.
     *
     * 用法 / Usage: 由本转换器写方向与覆盖门面的 CAS 更新调用。/ Used by the write direction of this converter and by the override
     * facade's compare-and-set writes.
     * @param value 参数 附加权限集合；parameter additional permissions.
     * @return 返回 jsonb 列值或 {@code null}；returns the jsonb column value or {@code null}.
     */
    public JsonNode permissionsNode(Set<String> value) {
        if (value == null) {
            return null;
        }
        try {
            return objectMapper.valueToTree(value);
        } catch (IllegalArgumentException failure) {
            throw new IllegalArgumentException(
                    "MCP persistence value cannot be serialized",
                    failure
            );
        }
    }

    /**
     * 中文说明：执行 stringSet 操作，把 jsonb 数组列值解码为不可变附加权限集合；列缺失或为 JSON {@code null} 时如实返回
     * {@code null}，结构不符沿用原「stored MCP string set is invalid」文案。
     * English summary: Executes the stringSet operation, decoding the jsonb array column value into an immutable permission set; an
     * absent column or a JSON {@code null} truthfully yields {@code null}, and a shape mismatch keeps the legacy
     * {@code stored MCP string set is invalid} message.
     *
     * 用法 / Usage: 仅由 {@link #toBusiness(McpManagedToolOverrideRecordPO)} 调用。
     * @param value 参数 jsonb 列值；parameter jsonb column value。
     * @return 返回 附加权限集合或 {@code null}；returns the permission set or {@code null}.
     */
    private Set<String> stringSet(JsonNode value) {
        if (value == null || value.isNull()) {
            return null;
        }
        try {
            return Set.copyOf(objectMapper.convertValue(value, STRING_SET));
        } catch (IllegalArgumentException failure) {
            throw new IllegalStateException(
                    "stored MCP string set is invalid",
                    failure
            );
        }
    }
}

/**
 * 中文说明：{@code McpManagedToolOverrideMapping} 是 {@code gateway_mcp_managed_tool_override} 的 MapStruct 结构映射契约，逐列复刻
 * 被替换的手写 JDBC 语义：{@code tool_id} 仍是端口使用的协议编号，组/操作/服务器三列在文本与 {@code bigint} 之间换算，
 * 计数式修订的可空列读作 0（等价原 {@code getLong}）；{@code additional_permissions} 在两个方向都显式忽略，
 * 因为 jsonb 编解码只由外部转换器经 Spring 托管的 {@code jacksonObjectMapper} 完成；受保护技术列全部忽略，因为
 * {@code EgonColaMetaObjectHandler} 独占租户、审计、软删与 MP 版本列（旧语句的 {@code created_by}/{@code updated_by}
 * 由边界的 {@code create_user_id}/{@code update_user_id} 承担）；{@code unmappedTargetPolicy=ERROR} 保证任何新增列都必须在此
 * 显式表态。
 * English summary: {@code McpManagedToolOverrideMapping} is the MapStruct structural contract for
 * {@code gateway_mcp_managed_tool_override}, mirroring the hand-written JDBC it replaces column by column: {@code tool_id} stays the
 * protocol identifier the port carries while the group, operation and server columns are converted between decimal text and
 * {@code bigint}, and a null revision reads as 0 (the legacy {@code getLong}); {@code additional_permissions} is ignored explicitly in
 * both directions because its jsonb codec runs in the enclosing converter through the Spring-managed
 * {@code jacksonObjectMapper}; every protected technical column stays ignored because {@code EgonColaMetaObjectHandler} owns the
 * tenant, audit, soft-delete and MP version columns (the legacy {@code created_by}/{@code updated_by} are carried by the boundary's
 * {@code create_user_id}/{@code update_user_id}); {@code unmappedTargetPolicy=ERROR} forces every new column to be stated explicitly
 * here.
 *
 * 用法 / Usage: 由 {@link McpManagedToolOverridePersistenceConverter} 通过 {@code Mappers} 持有，不对外暴露，也不登记为 Spring bean。
 * Held by {@link McpManagedToolOverridePersistenceConverter} through {@code Mappers}; neither published to callers nor registered as a
 * bean.
 */
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
interface McpManagedToolOverrideMapping {

    /**
     * 中文说明：执行 toBusiness 操作，按 {@code McpManagedToolOverrideBO} 的字段顺序投影受管工具覆盖行。
     * English summary: Executes the toBusiness operation, projecting an override row onto {@code McpManagedToolOverrideBO}.
     *
     * 用法 / Usage: 仅由 {@link McpManagedToolOverridePersistenceConverter#toBusiness(McpManagedToolOverrideRecordPO)} 调用。
     * @param source 参数 行模型；parameter row model。
     * @return 返回 业务载体；returns the business carrier.
     */
    @BeanMapping(builder = @Builder(disableBuilder = true))
    @Mapping(target = "toolId", source = "toolId")
    @Mapping(target = "gatewayGroupId", expression = "java( text( source.getGatewayGroupId() ) )")
    @Mapping(target = "operationId", expression = "java( text( source.getOperationId() ) )")
    @Mapping(target = "serverId", expression = "java( text( source.getServerId() ) )")
    @Mapping(target = "additionalPermissions", ignore = true)
    @Mapping(target = "minimumRiskLevel", source = "minimumRiskLevel")
    @Mapping(target = "enabled", source = "enabled")
    @Mapping(target = "revision", expression = "java( revision( source.getRevision() ) )")
    McpManagedToolOverrideBO toBusiness(McpManagedToolOverrideRecordPO source);

    /**
     * 中文说明：执行 toRow 操作，把受管工具覆盖载体写回行模型；技术主键留空由 {@code ASSIGN_ID} 生成，
     * 组/操作/服务器三列换算为 {@code bigint} 外键，受保护技术列与 jsonb 列一律忽略。
     * English summary: Executes the toRow operation, writing the override carrier back onto the row model; the technical primary key
     * stays empty for {@code ASSIGN_ID}, the group, operation and server columns become {@code bigint} foreign keys, and every
     * protected technical column plus the jsonb column stays ignored.
     *
     * 用法 / Usage: 仅由 {@link McpManagedToolOverridePersistenceConverter#toPersistence(McpManagedToolOverrideBO)} 调用。
     * @param source 参数 业务载体；parameter business carrier。
     * @return 返回 行模型；returns the row model.
     */
    @BeanMapping(builder = @Builder(disableBuilder = true))
    @Mapping(target = "toolId", source = "toolId")
    @Mapping(target = "gatewayGroupId", expression = "java( identifier( source.getGatewayGroupId() ) )")
    @Mapping(target = "operationId", expression = "java( identifier( source.getOperationId() ) )")
    @Mapping(target = "serverId", expression = "java( identifier( source.getServerId() ) )")
    @Mapping(target = "additionalPermissions", ignore = true)
    @Mapping(target = "minimumRiskLevel", source = "minimumRiskLevel")
    @Mapping(target = "enabled", source = "enabled")
    @Mapping(target = "revision", source = "revision")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "tenantId", ignore = true)
    @Mapping(target = "createUserId", ignore = true)
    @Mapping(target = "createTime", ignore = true)
    @Mapping(target = "updateUserId", ignore = true)
    @Mapping(target = "updateTime", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "version", ignore = true)
    McpManagedToolOverrideRecordPO toRow(McpManagedToolOverrideBO source);

    /**
     * 中文说明：执行 text 操作，把 MP 的 bigint 外键列按十进制文本投影，等价于原 JDBC 的 {@code getString(...)}；
     * {@code null} 保持 {@code null}。
     * English summary: Executes the text operation, projecting an MP bigint foreign-key column as decimal text, exactly what the legacy
     * {@code getString(...)} produced; {@code null} stays {@code null}.
     *
     * 用法 / Usage: 映射表达式内部使用。/ Used from the mapping expressions only.
     * @param value 参数 外键列；parameter stored foreign key。
     * @return 返回 十进制文本；returns the decimal text.
     */
    default String text(Long value) {
        return value == null ? null : Long.toString(value);
    }

    /**
     * 中文说明：执行 identifier 操作，把端口的十进制标识换算为 MP bigint 外键；空白按「未指向资源」读作 {@code null}
     * （等价旧语句对可空 {@code server_id} 的 NULL 绑定），无法表示的标识按调用方契约错误抛出，而不是写出 {@code NULL}
     * 冒充外键成功。
     * English summary: Executes the identifier operation, converting the port's decimal identifier into the MP bigint foreign key;
     * blank reads as {@code null}, i.e. no linked resource (the legacy NULL binding of the nullable {@code server_id}), while an
     * unrepresentable identifier is raised as a caller contract error instead of writing {@code NULL} and pretending the link succeeded.
     *
     * 用法 / Usage: 映射表达式内部使用。/ Used from the mapping expressions only.
     * @param value 参数 业务标识；parameter business identifier。
     * @return 返回 外键列值或 {@code null}；returns the foreign-key column value or {@code null}.
     */
    default Long identifier(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        try {
            return Long.valueOf(value.trim());
        } catch (NumberFormatException invalidIdentifier) {
            throw new IllegalArgumentException(
                    "managed Tool override identifier must be decimal: " + value,
                    invalidIdentifier
            );
        }
    }

    /**
     * 中文说明：执行 revision 操作，把可空业务修订列投影为载体的 {@code long} 字段，等价原 {@code getLong("revision")}。
     * English summary: Executes the revision operation, narrowing a nullable business revision column onto the {@code long} carrier
     * field, equivalent to the legacy {@code getLong("revision")}.
     *
     * 用法 / Usage: 映射表达式内部使用。/ Used from the mapping expressions only.
     * @param value 参数 修订列；parameter stored revision。
     * @return 返回 修订；returns the revision.
     */
    default long revision(Long value) {
        return value == null ? 0L : value;
    }
}
