package top.egon.cola.component.yuheng.admin.mcp.converter;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.mapstruct.BeanMapping;
import org.mapstruct.Builder;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.factory.Mappers;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;
import top.egon.cola.component.common.core.converter.BaseConverter;
import top.egon.cola.component.yuheng.admin.mcp.domain.bo.McpTaskBO;
import top.egon.cola.component.yuheng.admin.mcp.domain.po.McpTaskRecordPO;

/**
 * 中文说明：{@code McpTaskPersistenceConverter} 是 {@code gateway_mcp_task_instance} 在持久边界唯一的 MapStruct 转换器，负责
 * {@link McpTaskRecordPO} 行模型与 {@link McpTaskBO} 业务载体之间的双向映射：端口上的异步任务编号落在协议列
 * {@code task_key}（技术 {@code id} 由边界生成，写方向绝不触碰），MCP 主体租户落在 {@code subject_tenant_id}
 * （MP 的 {@code tenant_id} 是管理面上下文租户，两者互不替代），{@code state} 按 wire 字面量原样读写（永不 ordinal），
 * 三个可空 jsonb 负载列经 Spring 托管的 Jackson 在 {@code JsonNode} 与 {@code Map<String, Object>} 之间往返
 * ——写入为 {@code null} 时留空由门面显式下推 SQL NULL（等价被替换的 {@code ?::jsonb} 空文本绑定），读取时 SQL NULL
 * 与 JSON {@code null} 一律投影为 {@code null}；{@code attempt_count}/{@code max_attempts} 与业务 {@code revision}
 * 的列空值按原 {@code getInt/getLong} 读作 0；createdAt/updatedAt 只读投影自 MP 审计列。
 * English summary: {@code McpTaskPersistenceConverter} is the only MapStruct converter at the persistence boundary of
 * {@code gateway_mcp_task_instance}, mapping {@link McpTaskRecordPO} rows and {@link McpTaskBO} carriers both ways: the
 * protocol task identifier lives in {@code task_key} (the technical {@code id} is generated by the guarded boundary and is
 * never written from this side), the MCP subject tenant lives in {@code subject_tenant_id} (the MP {@code tenant_id} is the
 * management-plane context tenant and neither replaces the other), {@code state} travels as its wire literal (never an
 * ordinal), and the three nullable jsonb payload columns round-trip through the Spring-managed Jackson mapper between a
 * {@code JsonNode} and a {@code Map<String, Object>} — an absent carrier value is left unset here so the facade pushes an
 * explicit SQL NULL (the equivalent of the replaced {@code ?::jsonb} null-text binding), while a SQL NULL and a JSON
 * {@code null} both project to {@code null} on read; null {@code attempt_count}/{@code max_attempts}/{@code revision}
 * columns read as 0 exactly like the legacy {@code getInt/getLong}, and createdAt/updatedAt are read-only projections of the
 * MP audit columns.
 *
 * 用法 / Usage: 由 {@code gateway_mcp_task_instance} 的受守卫 MP 门面注入（bean 名 {@code mcpTaskPersistenceConverter}）；
 * 写方向不触碰租户、审计、软删、版本与技术主键，因为它们由 {@code EgonColaMetaObjectHandler} 与 {@code ASSIGN_ID} 独占，
 * 业务 CAS 列 {@code revision} 与 MP {@code version} 互不替代。JSON 列编解码只在此处经
 * {@code jacksonObjectMapper} 完成，门面需要单独写负载时调用 {@link #payloadNode(Map)}。
 * Injected by the guarded {@code gateway_mcp_task_instance} facade under the bean name {@code mcpTaskPersistenceConverter};
 * the write direction never touches the tenant, audit, soft-delete, version or technical identifier columns because
 * {@code EgonColaMetaObjectHandler} and {@code ASSIGN_ID} own them, while the business CAS column {@code revision} stays
 * independent of the MP {@code version}. JSON column encoding and decoding happen only here through
 * {@code jacksonObjectMapper}; a facade that writes a single payload calls {@link #payloadNode(Map)}.
 */
@Slf4j
@Component("mcpTaskPersistenceConverter")
@RequiredArgsConstructor
public class McpTaskPersistenceConverter implements BaseConverter<
        McpTaskRecordPO,
        McpTaskBO> {

    /**
     * 中文说明：表示 MapStruct 生成的同包结构映射器实例，本类只补充 jsonb 编解码、空值守护与日志边界。
     * English summary: The MapStruct generated same-package structural mapper; this class only adds jsonb codec, null
     * guarding and logging.
     *
     * 用法 / Usage: 仅由本转换器的公开方法调用。/ Invoked only by the public methods of this converter.
     */
    private static final McpTaskMapping MAPPING =
            Mappers.getMapper(McpTaskMapping.class);

    /**
     * 中文说明：表示 TASK_PAYLOAD 这一固定值，声明三个 jsonb 负载列的结构化载体类型，与原持久化边界的
     * {@code Map<String, Object>} 读型一致。
     * English summary: Represents the fixed task payload value, the structured carrier type of the three jsonb payload
     * columns, identical to the {@code Map<String, Object>} read type of the replaced persistence boundary.
     *
     * 用法 / Usage: 仅由本类的负载解码使用。/ Used only by the payload decoding of this class.
     */
    private static final TypeReference<Map<String, Object>> TASK_PAYLOAD =
            new TypeReference<>() {
            };

    @Qualifier("jacksonObjectMapper")
    private final ObjectMapper objectMapper;

    /**
     * 中文说明：执行 toPersistence 操作，把异步任务载体渲染为 MP 行模型，并编码三个可空 jsonb 负载列。
     * English summary: Executes the toPersistence operation, rendering an asynchronous task carrier into the MyBatis-Plus row
     * model and encoding the three nullable jsonb payload columns.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpTaskPersistenceConverter.toPersistence(taskBO)}。传入 {@code null} 返回 {@code null}。
     * Passing {@code null} returns {@code null}.
     * @param carrier 参数 业务载体；parameter business carrier。
     * @return 返回 行模型；returns the row model.
     */
    public McpTaskRecordPO toPersistence(McpTaskBO carrier) {
        if (carrier == null) {
            log.debug("gateway_mcp_task_instance business carrier is absent; no row rendered");
            return null;
        }
        McpTaskRecordPO row = MAPPING.toRow(carrier);
        row.setInputPayload(payloadNode(carrier.getInputPayload()));
        row.setResultPayload(payloadNode(carrier.getResultPayload()));
        row.setErrorPayload(payloadNode(carrier.getErrorPayload()));
        return row;
    }

    /**
     * 中文说明：执行 toBusiness 操作，把异步任务行投影为业务载体，解码三个 jsonb 负载列。
     * English summary: Executes the toBusiness operation, projecting a task row onto the business carrier and decoding the
     * three jsonb payload columns.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpTaskPersistenceConverter.toBusiness(row)}。传入 {@code null} 返回 {@code null}。
     * Passing {@code null} returns {@code null}.
     * @param row 参数 行模型；parameter row model。
     * @return 返回 业务载体；returns the business carrier.
     */
    public McpTaskBO toBusiness(McpTaskRecordPO row) {
        if (row == null) {
            log.debug("gateway_mcp_task_instance row is absent; no business carrier projected");
            return null;
        }
        McpTaskBO carrier = MAPPING.toBusiness(row);
        carrier.setInputPayload(payload(row.getInputPayload()));
        carrier.setResultPayload(payload(row.getResultPayload()));
        carrier.setErrorPayload(payload(row.getErrorPayload()));
        return carrier;
    }

    /**
     * 中文说明：执行 toPersistenceList 操作，按列表顺序渲染异步任务载体。
     * English summary: Executes the toPersistenceList operation, rendering every task carrier in order; null or empty input
     * yields an empty list and never {@code null}.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpTaskPersistenceConverter.toPersistenceList(carriers)}。
     * @param carriers 参数 业务载体列表；parameter business carriers.
     * @return 返回 行模型列表；returns the row models.
     */
    public List<McpTaskRecordPO> toPersistenceList(List<McpTaskBO> carriers) {
        return toSourceList(carriers);
    }

    /**
     * 中文说明：执行 toBusinessList 操作，按列表顺序投影异步任务行。
     * English summary: Executes the toBusinessList operation, projecting every task row in order; null or empty input yields
     * an empty list and never {@code null}.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpTaskPersistenceConverter.toBusinessList(rows)}。
     * @param rows 参数 行模型列表；parameter row models.
     * @return 返回 业务载体列表；returns the business carriers.
     */
    public List<McpTaskBO> toBusinessList(List<McpTaskRecordPO> rows) {
        return toTargetList(rows);
    }

    /**
     * 中文说明：执行 toTarget 操作，即 {@code BaseConverter} 的正向投影（行模型 -> 业务载体）。
     * English summary: Executes the toTarget operation, the forward projection of {@code BaseConverter} (row model to business
     * carrier).
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpTaskPersistenceConverter.toTarget(row)}。
     * @param source 参数 行模型；parameter row model。
     * @return 返回 业务载体；returns the business carrier.
     */
    @Override
    public McpTaskBO toTarget(McpTaskRecordPO source) {
        return toBusiness(source);
    }

    /**
     * 中文说明：执行 toSource 操作，即 {@code BaseConverter} 的反向渲染（业务载体 -> 行模型）。
     * English summary: Executes the toSource operation, the reverse rendering of {@code BaseConverter} (business carrier to row
     * model).
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpTaskPersistenceConverter.toSource(carrier)}。
     * @param target 参数 业务载体；parameter business carrier。
     * @return 返回 行模型；returns the row model.
     */
    @Override
    public McpTaskRecordPO toSource(McpTaskBO target) {
        return toPersistence(target);
    }

    /**
     * 中文说明：执行 newRow 操作，是 {@code toPersistence} 的插入别名，语义为「只带业务列的新行」，
     * 技术主键、租户、审计、软删与版本列一律留空交由受守卫边界补齐。
     * English summary: Executes the newRow operation, an insert alias of {@code toPersistence} producing a row carrying business
     * columns only; the technical identifier and the tenant, audit, soft-delete and version columns stay empty for the
     * guarded boundary to fill.
     *
     * 用法 / Usage: 调用方式 / Usage: {@code mcpTaskPersistenceConverter.newRow(taskBO)}。
     * @param carrier 参数 业务载体；parameter business carrier。
     * @return 返回 待插入行模型；returns the row model to insert.
     */
    public McpTaskRecordPO newRow(McpTaskBO carrier) {
        return toPersistence(carrier);
    }

    /**
     * 中文说明：执行 payloadNode 操作，把结构化负载编码为 jsonb 列值；{@code null} 如实返回 {@code null}，
     * 由门面在 CAS 条件上显式下推 SQL NULL（等价被替换的 {@code ?::jsonb} 空文本绑定），编码失败沿用原
     * 「MCP persistence value cannot be serialized」文案。
     * English summary: Executes the payloadNode operation, encoding a structured payload into the jsonb column value;
     * {@code null} truthfully yields {@code null} so the facade pushes an explicit SQL NULL on the CAS condition (the
     * equivalent of the replaced {@code ?::jsonb} null-text binding), and an encoding failure keeps the legacy
     * {@code MCP persistence value cannot be serialized} message.
     *
     * 用法 / Usage: 由本转换器写方向与任务门面的状态推进调用。/ Used by the write direction of this converter and by the task
     * facade's state transitions.
     * @param value 参数 结构化负载；parameter structured payload。
     * @return 返回 jsonb 列值或 {@code null}；returns the jsonb column value or {@code null}.
     */
    public JsonNode payloadNode(Map<String, Object> value) {
        if (value == null) {
            return null;
        }
        try {
            return objectMapper.valueToTree(value);
        } catch (IllegalArgumentException failure) {
            throw new IllegalArgumentException(
                    "MCP persistence value cannot be serialized",
                    failure
            );
        }
    }

    /**
     * 中文说明：执行 payload 操作，把 jsonb 列值解码为结构化负载；SQL NULL 与 JSON {@code null} 都投影为 {@code null}，
     * 结构与原持久化边界一致地做不可变复制，解码失败沿用原「stored MCP persistence value is invalid」文案。
     * English summary: Executes the payload operation, decoding a jsonb column value into the structured payload; a SQL NULL
     * and a JSON {@code null} both project to {@code null}, the shape is defensively copied into an immutable view exactly as
     * the replaced persistence boundary did, and a decoding failure keeps the legacy
     * {@code stored MCP persistence value is invalid} message.
     *
     * 用法 / Usage: 仅由 {@link #toBusiness(McpTaskRecordPO)} 调用。
     * @param value 参数 jsonb 列值；parameter jsonb column value。
     * @return 返回 结构化负载或 {@code null}；returns the structured payload or {@code null}.
     */
    private Map<String, Object> payload(JsonNode value) {
        if (value == null || value.isNull()) {
            return null;
        }
        try {
            return Map.copyOf(objectMapper.convertValue(value, TASK_PAYLOAD));
        } catch (IllegalArgumentException failure) {
            throw new IllegalStateException(
                    "stored MCP persistence value is invalid",
                    failure
            );
        }
    }
}

/**
 * 中文说明：{@code McpTaskMapping} 是 {@code gateway_mcp_task_instance} 的 MapStruct 结构映射契约，逐列复刻被替换的手写 JDBC
 * 语义：{@code task_key} 与 {@code subject_tenant_id} 是端口编号与 MCP 主体租户的落位列，三个 jsonb 目标在本接口显式忽略
 * （编解码由外部转换器经 Spring 托管的 {@code jacksonObjectMapper} 完成，映射接口不持有裸序列化器），
 * 计数与修订的空列按原 JDBC 读作 0；受保护技术列全部忽略，因为
 * {@code EgonColaMetaObjectHandler} 独占租户、审计、软删与 MP 版本列；{@code unmappedTargetPolicy=ERROR}
 * 保证任何新增列都必须在此显式表态。
 * English summary: {@code McpTaskMapping} is the MapStruct structural contract for {@code gateway_mcp_task_instance},
 * mirroring the hand-written JDBC it replaces column by column: {@code task_key} and {@code subject_tenant_id} are where the
 * port identifier and the MCP subject tenant land, the three jsonb targets are ignored explicitly here (their codec runs in
 * the enclosing converter through the Spring-managed {@code jacksonObjectMapper}, so this interface holds no raw serializer),
 * and null counter and revision columns read as 0 like the legacy JDBC did; every protected technical column stays ignored
 * because {@code EgonColaMetaObjectHandler} owns the tenant, audit, soft-delete and MP version columns;
 * {@code unmappedTargetPolicy=ERROR} forces every new column to be stated explicitly here.
 *
 * 用法 / Usage: 由 {@link McpTaskPersistenceConverter} 通过 {@code Mappers} 持有，不对外暴露，也不登记为 Spring bean。
 * Held by {@link McpTaskPersistenceConverter} through {@code Mappers}; neither published to callers nor registered as a bean.
 */
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
interface McpTaskMapping {

    /**
     * 中文说明：执行 toBusiness 操作，按 {@code McpTaskBO} 的字段顺序投影异步任务行。
     * English summary: Executes the toBusiness operation, projecting a task row onto {@code McpTaskBO}.
     *
     * 用法 / Usage: 仅由 {@link McpTaskPersistenceConverter#toBusiness(McpTaskRecordPO)} 调用。
     * @param source 参数 行模型；parameter row model。
     * @return 返回 业务载体；returns the business carrier.
     */
    @BeanMapping(builder = @Builder(disableBuilder = true))
    @Mapping(target = "id", source = "taskKey")
    @Mapping(target = "principalFingerprint", source = "principalFingerprint")
    @Mapping(target = "subjectId", source = "subjectId")
    @Mapping(target = "tenantId", source = "subjectTenantId")
    @Mapping(target = "clientId", source = "clientId")
    @Mapping(target = "serverCode", source = "serverCode")
    @Mapping(target = "toolName", source = "toolName")
    @Mapping(target = "requestDigest", source = "requestDigest")
    @Mapping(target = "state", source = "state")
    @Mapping(target = "inputPayload", ignore = true)
    @Mapping(target = "resultPayload", ignore = true)
    @Mapping(target = "errorPayload", ignore = true)
    @Mapping(target = "workerOwner", source = "workerOwner")
    @Mapping(target = "leaseUntil", source = "leaseUntil")
    @Mapping(target = "executionDeadline", source = "executionDeadline")
    @Mapping(target = "expiresAt", source = "expiresAt")
    @Mapping(target = "attemptCount", expression = "java( count( source.getAttemptCount() ) )")
    @Mapping(target = "maxAttempts", expression = "java( count( source.getMaxAttempts() ) )")
    @Mapping(target = "revision", expression = "java( revision( source.getRevision() ) )")
    @Mapping(target = "createdAt", source = "createTime")
    @Mapping(target = "updatedAt", source = "updateTime")
    McpTaskBO toBusiness(McpTaskRecordPO source);

    /**
     * 中文说明：执行 toRow 操作，把异步任务载体写回行模型；技术主键留空由 {@code ASSIGN_ID} 生成，端口编号写进
     * 协议列 {@code task_key}，主体租户写进 {@code subject_tenant_id}，受保护技术列全部忽略。
     * English summary: Executes the toRow operation, writing the task carrier back onto the row model; the technical primary
     * key stays empty for {@code ASSIGN_ID}, the port identifier is written into the protocol column {@code task_key}, the
     * subject tenant into {@code subject_tenant_id}, and every protected technical column stays ignored.
     *
     * 用法 / Usage: 仅由 {@link McpTaskPersistenceConverter#toPersistence(McpTaskBO)} 调用。
     * @param source 参数 业务载体；parameter business carrier。
     * @return 返回 行模型；returns the row model.
     */
    @BeanMapping(builder = @Builder(disableBuilder = true))
    @Mapping(target = "taskKey", source = "id")
    @Mapping(target = "subjectTenantId", source = "tenantId")
    @Mapping(target = "principalFingerprint", source = "principalFingerprint")
    @Mapping(target = "subjectId", source = "subjectId")
    @Mapping(target = "clientId", source = "clientId")
    @Mapping(target = "serverCode", source = "serverCode")
    @Mapping(target = "toolName", source = "toolName")
    @Mapping(target = "requestDigest", source = "requestDigest")
    @Mapping(target = "state", source = "state")
    @Mapping(target = "inputPayload", ignore = true)
    @Mapping(target = "resultPayload", ignore = true)
    @Mapping(target = "errorPayload", ignore = true)
    @Mapping(target = "workerOwner", source = "workerOwner")
    @Mapping(target = "leaseUntil", source = "leaseUntil")
    @Mapping(target = "executionDeadline", source = "executionDeadline")
    @Mapping(target = "expiresAt", source = "expiresAt")
    @Mapping(target = "attemptCount", source = "attemptCount")
    @Mapping(target = "maxAttempts", source = "maxAttempts")
    @Mapping(target = "revision", source = "revision")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "tenantId", ignore = true)
    @Mapping(target = "createUserId", ignore = true)
    @Mapping(target = "createTime", ignore = true)
    @Mapping(target = "updateUserId", ignore = true)
    @Mapping(target = "updateTime", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "version", ignore = true)
    McpTaskRecordPO toRow(McpTaskBO source);

    /**
     * 中文说明：执行 count 操作，把可空计数列投影为载体的 {@code int} 字段，等价原 JDBC 的
     * {@code getInt("attempt_count")}（列缺失即 0）。
     * English summary: Executes the count operation, narrowing a nullable counter column onto the {@code int} carrier field,
     * equivalent to the legacy {@code getInt("attempt_count")} which yields 0 for an absent value.
     *
     * 用法 / Usage: 映射表达式内部使用。/ Used from the mapping expressions only.
     * @param value 参数 计数列；parameter stored counter。
     * @return 返回 计数；returns the counter.
     */
    default int count(Integer value) {
        return value == null ? 0 : value;
    }

    /**
     * 中文说明：执行 revision 操作，把可空业务修订列投影为载体的 {@code long} 字段，等价原
     * {@code getLong("revision")}。
     * English summary: Executes the revision operation, narrowing a nullable business revision column onto the {@code long}
     * carrier field, equivalent to the legacy {@code getLong("revision")}.
     *
     * 用法 / Usage: 映射表达式内部使用。/ Used from the mapping expressions only.
     * @param value 参数 修订列；parameter stored revision。
     * @return 返回 修订；returns the revision.
     */
    default long revision(Long value) {
        return value == null ? 0L : value;
    }
}
