server:
  address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gatewayTls

egon:
  cola:
    component:
      gateway:
        engine:
          tls-reload:
            enabled: true
