syntax = "proto3";

package egon.yuheng.schema.v1;

option java_package =
    "top.egon.cola.component.yuheng.contract.schema.proto";
option java_multiple_files = true;

import "google/protobuf/descriptor.proto";

enum GatewayRequiredOption {
  YUHENG_REQUIRED_AUTO = 0;
  YUHENG_REQUIRED = 1;
  YUHENG_OPTIONAL = 2;
}

message GatewaySchemaFieldOption {
  string description = 1;
  string format = 2;
  GatewayRequiredOption required = 3;
  string example = 4;
}

extend google.protobuf.FieldOptions {
  GatewaySchemaFieldOption yuheng_schema = 51001;
}
