package top.egon.cola.archetype.source.webopen.infrastructure.config.datasource;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import top.egon.cola.component.common.mybatis.ddl.EgonColaDdlManifestBO;

import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.HexFormat;

import static org.assertj.core.api.Assertions.assertThat;

class PostgreSqlSchemaInitializationTest {

    @Test
    void completeInitializationHasAnExactManifestAndNoLegacyExecution() throws Exception {
        Path resources = Path.of("src/main/resources");
        EgonColaDdlManifestBO manifest = new ObjectMapper().readValue(
                resources.resolve("db/egon-mp/repository-manifest.json").toFile(), EgonColaDdlManifestBO.class);
        assertThat(manifest.family()).isEqualTo("web-open");
        assertThat(manifest.scripts()).hasSize(1);
        var script = manifest.scripts().getFirst();
        byte[] content = Files.readAllBytes(resources.resolve(script.path()));
        assertThat(script.sha256()).isEqualTo(HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(content)));
        String sql = new String(content, java.nio.charset.StandardCharsets.UTF_8);
        assertThat(sql).contains("ddl_history", "tenant_id BIGINT NOT NULL", "deleted_at TIMESTAMP(6) WITHOUT TIME ZONE", "version BIGINT NOT NULL DEFAULT 0");
        assertThat(sql).doesNotContain("is_deleted", "flyway_schema_history", "1970-01-01", "DROP TABLE", "GENERATED BY DEFAULT AS IDENTITY");
        assertThat(sql).contains("WHERE deleted_at IS NULL", "egon_migration.role");
    }
}
