package top.egon.cola.component.rag.converter;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.factory.Mappers;
import org.springframework.ai.document.Document;
import top.egon.cola.component.rag.metadata.RagMetadataKeys;
import top.egon.cola.component.rag.model.RagChunkBO;
import top.egon.cola.component.rag.model.RagRetrievedChunkBO;
import top.egon.cola.component.common.core.converter.BaseConverter;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Maps between the component's chunk model and the framework's vector document.
 *
 * <p>The converter's pair is the retrieved chunk and the vector document: that mapping is a genuine
 * field mapping and is generated by MapStruct, with the metadata-derived fields resolved through the
 * static helpers below. Writing an ingested chunk is not a mapping of that pair — a chunk carries no
 * identifier and no metadata — so it is a factory method with an explicit signature.
 *
 * <p>{@code unmappedTargetPolicy = ERROR} keeps both directions honest: a new field on either side
 * fails the build instead of being silently dropped.
 */
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface RagChunkConverter extends BaseConverter<RagRetrievedChunkBO, Document> {

    RagChunkConverter INSTANCE = Mappers.getMapper(RagChunkConverter.class);

    /**
     * Builds the vector document for one chunk.
     *
     * <p>Not a bean mapping: {@code chunkId} and {@code metadata} are derived by the caller from the
     * document identity and the reserved keys, so they are parameters rather than mapped properties.
     */
    default Document toDocument(RagChunkBO source, String chunkId, Map<String, Object> metadata) {
        return new Document(chunkId, source.content(), metadata);
    }

    /** Rebuilds a vector document from a retrieved chunk, restoring the reserved metadata keys. */
    @Override
    default Document toTarget(RagRetrievedChunkBO source) {
        Map<String, Object> metadata = new LinkedHashMap<>();
        metadata.put(RagMetadataKeys.COLLECTION_ID, source.collectionId());
        metadata.put(RagMetadataKeys.DOCUMENT_ID, source.documentId());
        metadata.put(RagMetadataKeys.CHUNK_INDEX, source.chunkIndex());
        metadata.put(RagMetadataKeys.LOGICAL_MODEL_NAME, source.logicalModelName());
        metadata.putAll(source.attributes());
        return new Document(source.chunkId(), source.content(), metadata);
    }

    @Mapping(target = "chunkId", source = "id")
    @Mapping(target = "content", source = "text")
    @Mapping(target = "score", source = "score")
    @Mapping(target = "collectionId", expression = "java(RagChunkConverter.text(target, top.egon.cola.component.rag.metadata.RagMetadataKeys.COLLECTION_ID))")
    @Mapping(target = "documentId", expression = "java(RagChunkConverter.text(target, top.egon.cola.component.rag.metadata.RagMetadataKeys.DOCUMENT_ID))")
    @Mapping(target = "logicalModelName", expression = "java(RagChunkConverter.text(target, top.egon.cola.component.rag.metadata.RagMetadataKeys.LOGICAL_MODEL_NAME))")
    @Mapping(target = "chunkIndex", expression = "java(RagChunkConverter.number(target, top.egon.cola.component.rag.metadata.RagMetadataKeys.CHUNK_INDEX))")
    @Mapping(target = "attributes", expression = "java(RagChunkConverter.businessAttributes(target))")
    @Override
    RagRetrievedChunkBO toSource(Document target);

    /** Reads a metadata value as text; {@code null} when absent. */
    static String text(Document document, String key) {
        Map<String, Object> metadata = document.getMetadata();
        Object value = metadata == null ? null : metadata.get(key);
        return value == null ? null : String.valueOf(value);
    }

    /** Reads a metadata value as an integer; zero when absent or unparseable. */
    static int number(Document document, String key) {
        Map<String, Object> metadata = document.getMetadata();
        Object value = metadata == null ? null : metadata.get(key);
        if (value instanceof Number number) {
            return number.intValue();
        }
        try {
            return value == null ? 0 : Integer.parseInt(String.valueOf(value));
        } catch (NumberFormatException exception) {
            return 0;
        }
    }

    /** Copies every non-reserved metadata entry out as text, preserving its order. */
    static Map<String, String> businessAttributes(Document document) {
        Map<String, Object> metadata = document.getMetadata();
        if (metadata == null || metadata.isEmpty()) {
            return Map.of();
        }
        Map<String, String> attributes = new LinkedHashMap<>();
        metadata.forEach((key, value) -> {
            if (!RagMetadataKeys.reservedKeys().contains(key) && value != null) {
                attributes.put(key, String.valueOf(value));
            }
        });
        return Map.copyOf(attributes);
    }
}
