spring:
  application:
    name: light
  datasource:
    url: jdbc:h2:mem:light;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: ${DUBBO_REGISTRY_ADDRESS:N/A}
  protocol:
    name: tri
    port: ${DUBBO_PORT:50051}
  provider:
    timeout: 3000
    retries: 0
