sourceProject=source-projects/egon-cola-source-light-open
sourceGroupId=top.egon.internal.archetype.source
sourceArtifactId=egon-cola-source-light-open
sourceVersion=0.1.0-SNAPSHOT
sourcePackage=top.egon.cola.archetype.source.lightopen
targetArtifactId=egon-cola-archetype-light-open
expectedTopology=root
