syntax = "proto3";

package egon.evaluation.v1;

import "google/protobuf/timestamp.proto";

option java_multiple_files = true;
option java_package = "top.egon.cola.archetype.source.serviceopen.facade.evaluation.v1";

service ExamService {
  rpc CreateExam(CreateExamRequest) returns (Exam);
  rpc AttachPaper(AttachExamPaperRequest) returns (ExamPaper);
  rpc PublishExam(PublishExamRequest) returns (Exam);
  rpc GetExam(GetExamRequest) returns (Exam);
}

message CreateExamRequest {
  int64 course_id = 1;
  string title = 2;
  google.protobuf.Timestamp starts_at = 3;
  google.protobuf.Timestamp ends_at = 4;
}

message AttachExamPaperRequest {
  int64 exam_id = 1;
  string title = 2;
  int32 total_points = 3;
}

message PublishExamRequest {
  int64 exam_id = 1;
}

message GetExamRequest {
  int64 exam_id = 1;
}

message Exam {
  int64 id = 1;
  int64 course_id = 2;
  string title = 3;
  google.protobuf.Timestamp starts_at = 4;
  google.protobuf.Timestamp ends_at = 5;
  string status = 6;
}

message ExamPaper {
  int64 id = 1;
  int64 exam_id = 2;
  string title = 3;
  int32 total_points = 4;
  string status = 5;
}
