-- knowledge 域建表：扩展、知识库表与文档表属于同一个数据库变更面，不拆分为多条迁移。
-- 向量表由 PgVectorStore 以 initializeSchema 自建，不进入 Flyway 版本管理。
create extension if not exists vector;

create table knowledge_base (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 0,
    create_user_id varchar(64),
    create_time timestamp with time zone not null,
    update_user_id varchar(64),
    update_time timestamp with time zone not null,
    is_deleted boolean not null default false,
    code varchar(64) not null,
    name varchar(128) not null,
    description varchar(512),
    embedding_model varchar(32) not null,
    chunk_strategy varchar(32) not null,
    chunk_config jsonb not null,
    status varchar(16) not null default 'ACTIVE',
    constraint ck_knowledge_base_chunk_strategy check (
        chunk_strategy in ('TOKEN', 'MARKDOWN_HEADING', 'RECURSIVE')
    ),
    constraint ck_knowledge_base_status check (
        status in ('ACTIVE', 'DELETED')
    )
);

-- 业务键在租户内不区分大小写，软删行不占用业务键。
create unique index uk_knowledge_base_tenant_code
    on knowledge_base(tenant_id, lower(code))
    where is_deleted = false;

create index idx_knowledge_base_tenant_created
    on knowledge_base(tenant_id, create_time desc, id desc)
    where is_deleted = false;

create table knowledge_document (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 0,
    create_user_id varchar(64),
    create_time timestamp with time zone not null,
    update_user_id varchar(64),
    update_time timestamp with time zone not null,
    is_deleted boolean not null default false,
    knowledge_base_id bigint not null,
    display_name varchar(255) not null,
    file_name varchar(255),
    mime_type varchar(128),
    size_bytes bigint not null,
    content_hash char(64) not null,
    storage_type varchar(16) not null,
    storage_key varchar(512) not null,
    content text,
    status varchar(16) not null default 'PENDING',
    chunk_count integer not null default 0,
    attempt_count integer not null default 0,
    error_code varchar(64),
    error_message varchar(512),
    constraint ck_knowledge_document_status check (
        status in ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'DEAD')
    ),
    constraint ck_knowledge_document_storage_type check (
        storage_type in ('LOCAL')
    ),
    constraint ck_knowledge_document_size_bytes check (size_bytes >= 0),
    constraint ck_knowledge_document_chunk_count check (chunk_count >= 0),
    constraint ck_knowledge_document_attempt_count check (attempt_count >= 0)
);

create index idx_knowledge_document_tenant_base_created
    on knowledge_document(tenant_id, knowledge_base_id, create_time desc, id desc)
    where is_deleted = false;
