#set( $symbol_dollar = '$' )
spring:
  application:
    name: ${rootArtifactId}
  datasource:
    url: jdbc:h2:mem:${rootArtifactId};MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health,info

dubbo:
  application:
    name: ${symbol_dollar}{spring.application.name}
  registry:
    address: ${symbol_dollar}{DUBBO_REGISTRY_ADDRESS:N/A}
  protocol:
    name: tri
    port: ${symbol_dollar}{DUBBO_PORT:50051}
  provider:
    timeout: 3000
    retries: 0
