sourceProject=source-projects/egon-cola-source-web
sourceGroupId=top.egon.internal.archetype.source
sourceArtifactId=egon-cola-source-web
sourceVersion=0.1.0-SNAPSHOT
sourcePackage=top.egon.cola.archetype.source.web
targetArtifactId=egon-cola-archetype-web
expectedTopology=common,domain,application,infrastructure,adapter,starter
