spring:
  application:
    name: rpc-test-consumer

egon:
  cola:
    component:
      ddc:
        enabled: false
        rpc:
          target: ${DDC_RPC_TARGET:dns:///127.0.0.1:19080}
          load-balancing-policy: round_robin
          tls:
            development-plaintext: ${DDC_RPC_DEVELOPMENT_PLAINTEXT:true}
          auth:
            runtime:
              access-key: ${DDC_RPC_RUNTIME_ACCESS_KEY:}
              secret-key: ${DDC_RPC_RUNTIME_SECRET_KEY:}
            registry:
              access-key: ${DDC_RPC_REGISTRY_ACCESS_KEY:}
              secret-key: ${DDC_RPC_REGISTRY_SECRET_KEY:}
        registry:
          enabled: false
      rpc:
        enabled: false
        consumer:
          enabled: false
