CREATE TABLE users (
    id VARCHAR(64) PRIMARY KEY,
    external_id VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_external_id UNIQUE (external_id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE roles (
    code VARCHAR(64) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE permissions (
    code VARCHAR(128) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE user_roles (
    user_id VARCHAR(64) NOT NULL,
    role_code VARCHAR(64) NOT NULL,
    assigned_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, role_code),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_code) REFERENCES roles (code)
);

CREATE TABLE role_permissions (
    role_code VARCHAR(64) NOT NULL,
    permission_code VARCHAR(128) NOT NULL,
    granted_at TIMESTAMP NOT NULL,
    PRIMARY KEY (role_code, permission_code),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_code) REFERENCES roles (code),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_code) REFERENCES permissions (code)
);

CREATE TABLE school_classes (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    semester VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

ALTER TABLE courses ADD COLUMN course_code VARCHAR(64);
ALTER TABLE courses ADD COLUMN status VARCHAR(32) DEFAULT 'ACTIVE';
UPDATE courses SET course_code = id WHERE course_code IS NULL;
UPDATE courses SET status = 'ACTIVE' WHERE status IS NULL;
ALTER TABLE courses ALTER COLUMN course_code SET NOT NULL;
ALTER TABLE courses ALTER COLUMN status SET NOT NULL;
ALTER TABLE courses ADD CONSTRAINT uk_courses_code UNIQUE (course_code);

CREATE TABLE class_course_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_class_id VARCHAR(64) NOT NULL,
    course_id VARCHAR(64) NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_class_course_start UNIQUE (school_class_id, course_id, starts_at),
    CONSTRAINT fk_schedule_class FOREIGN KEY (school_class_id) REFERENCES school_classes (id),
    CONSTRAINT fk_schedule_course FOREIGN KEY (course_id) REFERENCES courses (id)
);

INSERT INTO users (id, external_id, name, email, status, created_at)
SELECT id, CONCAT('legacy-', id), name, email, status, created_at
FROM students;

INSERT INTO roles (code, name, status, created_at)
VALUES ('teacher', 'Teacher', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO permissions (code, name, status, created_at)
VALUES ('course:read', 'Read courses', 'ACTIVE', CURRENT_TIMESTAMP);
