#set( $symbol_dollar = '$' )
spring:
  flyway:
    enabled: ${symbol_dollar}{FLYWAY_ENABLED:true}
    validate-migration-naming: true
    baseline-on-migrate: ${symbol_dollar}{FLYWAY_BASELINE_ON_MIGRATE:false}
    validate-on-migrate: true
    clean-disabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

app:
  integrations:
    organization:
      enabled: ${symbol_dollar}{ORGANIZATION_FACADE_ENABLED:true}
      group: ${symbol_dollar}{ORGANIZATION_FACADE_GROUP:student-management-organization}
      version: ${symbol_dollar}{ORGANIZATION_FACADE_SERVICE_VERSION:1.0.0}
    rabbitmq:
      enabled: ${symbol_dollar}{RABBITMQ_ENABLED:true}
      listener-auto-startup: ${symbol_dollar}{RABBITMQ_LISTENER_AUTO_STARTUP:true}
