create table egon_cola_outbox_message (
    id bigint generated by default as identity primary key,
    message_id varchar(64) not null,
    idempotency_key varchar(256),
    message_fingerprint char(64) not null,
    channel varchar(64) not null,
    destination varchar(256) not null,
    payload text not null,
    content_type varchar(128) not null,
    schema_version varchar(32),
    headers_json text not null default '{}',
    trace_id varchar(128),
    status varchar(32) not null,
    attempt_count integer not null default 0,
    max_attempts integer not null,
    next_attempt_at timestamp with time zone not null,
    locked_by varchar(128),
    locked_until timestamp with time zone,
    last_error_code varchar(64),
    last_error_message text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    completed_at timestamp with time zone,
    constraint ck_outbox_status check (
        status in ('PENDING', 'PROCESSING', 'RETRY_WAIT', 'SUCCEEDED', 'DEAD')
    ),
    constraint ck_outbox_attempt_count check (attempt_count >= 0),
    constraint ck_outbox_max_attempts check (max_attempts >= 1)
);

create unique index uk_outbox_message_id
    on egon_cola_outbox_message(message_id);

create unique index uk_outbox_idempotency_key
    on egon_cola_outbox_message(idempotency_key)
    where idempotency_key is not null;

create index idx_outbox_claim
    on egon_cola_outbox_message(next_attempt_at, id)
    where status in ('PENDING', 'RETRY_WAIT');

create index idx_outbox_reclaim
    on egon_cola_outbox_message(locked_until, id)
    where status = 'PROCESSING';

create index idx_outbox_cleanup
    on egon_cola_outbox_message(completed_at, id)
    where status = 'SUCCEEDED';
