package top.egon.cola.archetype.source.serviceopen.contract;

import com.google.protobuf.Descriptors;
import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

/**
 * Frozen peer facade ownership of the service Open project.
 *
 * <p>This project generates only the evaluation protocol and consumes the organization protocol from
 * the peer Web Open facade artifact. The Java owner and the Maven coordinate move, while every
 * Protobuf package, service, method and field name stays on the wire exactly as before, because the
 * remote service name is derived from the Protobuf package rather than from the Java package.
 */
class OpenPeerFacadeContractTest {

    private static final String PROJECT_ROOT = "top.egon.cola.archetype.source.serviceopen";
    private static final String OWN_FACADE_ROOT = "top.egon.cola.archetype.source.serviceopen.facade";
    private static final String PEER_FACADE_ROOT = "top.egon.cola.archetype.source.webopen.facade";
    private static final String ORGANIZATION_CLIENT_PACKAGE =
            "top.egon.cola.archetype.source.serviceopen.infrastructure.client.organization..";

    private record Provider(String name, Set<String> methods) {
    }

    private record Protocol(String javaOwner, String wirePackage, List<String> carriers,
                            List<Provider> providers) {
    }

    private static final String COPIED_OWNER = OWN_FACADE_ROOT + ".organization.v1";

    private static final Protocol OWN = new Protocol(OWN_FACADE_ROOT + ".evaluation.v1", "egon.evaluation.v1",
            List.of("Course", "CourseSchedule", "Exam", "ExamPaper", "Score"),
            List.of(new Provider("CourseService", Set.of("createCourse", "scheduleCourse", "getCourse", "pageCourses")),
                    new Provider("ExamService", Set.of("createExam", "attachPaper", "publishExam", "getExam")),
                    new Provider("ScoreService", Set.of("recordScore", "getScore", "pageScores"))));

    private static final Protocol PEER = new Protocol(PEER_FACADE_ROOT + ".organization.v1", "egon.organization.v1",
            List.of("User", "Grade", "SchoolClass", "PermissionTree"),
            List.of(new Provider("UserService", Set.of("createUser", "getUser")),
                    new Provider("RoleService", Set.of("assignRole")),
                    new Provider("PermissionService", Set.of("grantPermission", "getPermissionTree")),
                    new Provider("GradeService", Set.of("createGrade", "getGrade")),
                    new Provider("SchoolClassService",
                            Set.of("createSchoolClass", "getSchoolClass", "assignUser"))));

    private static final JavaClasses OWN_PRODUCTION_CLASSES =
            new ClassFileImporter().importPackages(PROJECT_ROOT);

    @Test
    void generates_only_the_own_evaluation_protocol() {
        assertFrozenWire(OWN);
        assertThat(OWN.carriers().stream()
                .map(carrier -> descriptorOf(load(OWN.javaOwner() + "." + carrier)).getFile())
                .flatMap(file -> file.getServices().stream())
                .map(Descriptors.ServiceDescriptor::getFullName).collect(Collectors.toSet()))
                .as("only the evaluation services may be generated by this project")
                .containsExactlyInAnyOrderElementsOf(OWN.providers().stream()
                        .map(provider -> OWN.wirePackage() + "." + provider.name()).collect(Collectors.toSet()));
    }

    @Test
    void publishes_no_copied_peer_organization_protocol() {
        for (String type : List.of("User", "Grade", "SchoolClass", "PermissionTree",
                "UserService", "RoleService", "PermissionService", "GradeService", "SchoolClassService")) {
            assertThatExceptionOfType(ClassNotFoundException.class)
                    .as("%s must be published only by the peer facade artifact", type)
                    .isThrownBy(() -> Class.forName(COPIED_OWNER + "." + type));
        }
    }

    @Test
    void consumes_the_peer_organization_facade_artifact() {
        assertFrozenWire(PEER);
    }

    @Test
    void keeps_the_peer_contract_behind_the_organization_client() {
        noClasses().that().resideInAPackage(PROJECT_ROOT + "..")
                .and().resideOutsideOfPackage(ORGANIZATION_CLIENT_PACKAGE)
                .should().accessClassesThat().resideInAPackage(PEER_FACADE_ROOT + "..")
                .check(OWN_PRODUCTION_CLASSES);

        assertThat(accessedOwners("infrastructure.client.organization.impl.DubboOrganizationDirectoryClientImpl"))
                .as("the organization client must consume the peer facade services")
                .anyMatch(type -> type.startsWith(PEER_FACADE_ROOT + "."));
    }

    private static void assertFrozenWire(Protocol protocol) {
        for (String carrier : protocol.carriers()) {
            Class<?> message = load(protocol.javaOwner() + "." + carrier);
            assertThat(message.getPackageName()).as("%s java owner", carrier).isEqualTo(protocol.javaOwner());
            assertThat(descriptorOf(message).getFile().getPackage())
                    .as("%s wire package", carrier).isEqualTo(protocol.wirePackage());
        }
        for (Provider provider : protocol.providers()) {
            Class<?> service = load(protocol.javaOwner() + "." + provider.name());
            assertThat(service.isInterface()).as("%s stays a provider interface", provider.name()).isTrue();
            assertThat(staticValue(service, "SERVICE_NAME")).as("%s remote service name", provider.name())
                    .isEqualTo(protocol.wirePackage() + "." + provider.name());
            assertThat(staticValue(service, "JAVA_SERVICE_NAME")).as("%s java service name", provider.name())
                    .isEqualTo(protocol.javaOwner() + "." + provider.name());
            assertThat(unaryMethods(service)).as("%s method inventory", provider.name())
                    .containsExactlyInAnyOrderElementsOf(provider.methods());
        }
    }

    private static Set<String> unaryMethods(Class<?> service) {
        return Arrays.stream(service.getDeclaredMethods())
                .filter(method -> !method.getName().endsWith("Async"))
                .map(Method::getName).collect(Collectors.toSet());
    }

    private static Set<String> accessedOwners(String typeName) {
        return OWN_PRODUCTION_CLASSES.get(PROJECT_ROOT + "." + typeName).getAllAccessesFromSelf().stream()
                .map(access -> access.getTarget().getOwner().getFullName()).collect(Collectors.toSet());
    }

    private static String staticValue(Class<?> type, String field) {
        try {
            return (String) type.getField(field).get(null);
        } catch (ReflectiveOperationException exception) {
            throw new AssertionError(type + " must expose String " + field, exception);
        }
    }

    private static Descriptors.Descriptor descriptorOf(Class<?> message) {
        try {
            return (Descriptors.Descriptor) message.getMethod("getDescriptor").invoke(null);
        } catch (ReflectiveOperationException exception) {
            throw new AssertionError(message + " must expose static getDescriptor()", exception);
        }
    }

    private static Class<?> load(String typeName) {
        try {
            return Class.forName(typeName);
        } catch (ClassNotFoundException exception) {
            throw new AssertionError("Missing facade contract: " + typeName, exception);
        }
    }
}
