package top.egon.cola.component.common.id.snowflake;

import java.time.Instant;

/**
 * Decoded fields of a Snowflake ID using the fixed epoch 2026-01-01T00:00:00Z.
 * IDs generated by one generator instance are strictly increasing. Across nodes,
 * IDs are trend ordered but are not guaranteed to be strictly ordered globally.
 *
 * @param id the original encoded ID
 * @param generatedAt the decoded generation instant
 * @param elapsedMillis milliseconds elapsed since the fixed epoch
 * @param machineId the decoded machine identifier
 * @param sequence the decoded per-millisecond sequence
 */
public record SnowflakeId(long id, Instant generatedAt, long elapsedMillis,
                          int machineId, int sequence) {
}
