package top.egon.cola.component.rpc.exception;

public enum EgonRpcErrorCode {

    RPC_INVALID_CONTRACT,

    RPC_PROVIDER_START_FAILED,

    RPC_REGISTRATION_FAILED,

    RPC_GATEWAY_UNAVAILABLE,

    RPC_GATEWAY_AMBIGUOUS,

    RPC_SERVICE_NOT_FOUND,

    RPC_METHOD_NOT_FOUND,

    RPC_DEADLINE_EXCEEDED,

    RPC_CANCELLED,

    RPC_PROVIDER_UNAVAILABLE,

    RPC_INVALID_REQUEST,

    RPC_PROVIDER_REJECTED,

    RPC_INTERNAL
}
