CREATE TABLE users (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE school_classes (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    grade_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE school_class_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_id VARCHAR(160) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    school_class_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_school_class_user UNIQUE (grade_id, school_class_id, user_id)
);
