CREATE TABLE roles (
    id VARCHAR(64) PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE permissions (
    id VARCHAR(64) PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    role_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id VARCHAR(64) NOT NULL,
    permission_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_role_permission UNIQUE (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id)
);

CREATE TABLE grades (
    id VARCHAR(160) PRIMARY KEY,
    code VARCHAR(160) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

INSERT INTO grades(id, code, name, status, created_at)
SELECT CONCAT('legacy:', grade_name), grade_name, grade_name, 'ACTIVE', MIN(created_at)
FROM school_classes
GROUP BY grade_name;

ALTER TABLE school_classes ADD COLUMN grade_id VARCHAR(160);
ALTER TABLE school_classes ADD COLUMN status VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL;
UPDATE school_classes SET grade_id = CONCAT('legacy:', grade_name);
ALTER TABLE school_classes ALTER COLUMN grade_id SET NOT NULL;
ALTER TABLE school_classes
    ADD CONSTRAINT fk_school_classes_grade FOREIGN KEY (grade_id) REFERENCES grades(id);

CREATE INDEX idx_school_classes_grade_id ON school_classes(grade_id);
CREATE INDEX idx_user_roles_role_id ON user_roles(role_id);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions(permission_id);

INSERT INTO roles(id, code, name, status, created_at)
VALUES ('role-student', 'STUDENT', 'Student', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO permissions(id, code, name, type, status, created_at)
VALUES ('permission-class-read', 'CLASS_READ', 'Read school class', 'API', 'ACTIVE', CURRENT_TIMESTAMP);
