sourceProject=source-projects/egon-cola-source-service-open
sourceGroupId=top.egon.internal.archetype.source
sourceArtifactId=egon-cola-source-service-open
sourceVersion=0.1.0-SNAPSHOT
sourcePackage=top.egon.cola.archetype.source.serviceopen
targetArtifactId=egon-cola-archetype-service-open
expectedTopology=common,domain,application,infrastructure,adapter,starter,facade
