egon:
  cola:
    component:
      ddc:
        enabled: true
        app-code: demo-app
        env: dev
        namespace: default
        redis:
          enabled: false
        instance:
          lease-seconds: 30
          heartbeat-interval-seconds: 10
        registry:
          enabled: false
        consistency:
          fail-fast: false
