spring:
  application:
    name: gateway-test-http-provider

server:
  port: 0
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

gateway:
  test:
    service-version: ${GATEWAY_TEST_SERVICE_VERSION:1.0.0-live}

egon:
  cola:
    component:
      ddc:
        enabled: false
        registry:
          enabled: false
      gateway:
        reporting:
          enabled: false
          artifact-version: ${gateway.test.service-version}
