spring:
  application:
    name: gateway-test-http-provider

server:
  port: 0
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

egon:
  cola:
    component:
      ddc:
        enabled: false
        registry:
          enabled: false
      gateway:
        reporting:
          enabled: false
