#!/bin/bash
set -eEuo pipefail

SELF_PATH=$(realpath -- "$0")
readonly SELF_PATH
SELF_DIR=${SELF_PATH%/*}
readonly SELF_DIR
cd "$SELF_DIR"

BASH_BUDDY_ROOT="$(realpath -- bash-buddy)"
readonly BASH_BUDDY_ROOT
# shellcheck disable=SC1091
source "$BASH_BUDDY_ROOT/lib/trap_error_info.sh"
# shellcheck disable=SC1091
source "$BASH_BUDDY_ROOT/lib/common_utils.sh"
# shellcheck disable=SC1091
source "$BASH_BUDDY_ROOT/lib/maven_utils.sh"

PROJECT_ROOT_DIR="$(realpath -- "$SELF_DIR/..")"
readonly PROJECT_ROOT_DIR
export PROJECT_ROOT_DIR

readonly nl=$'\n' # new line

# shellcheck disable=SC2154
[ $# -ne 1 ] && cu::die "need only 1 argument for version!$nl${nl}usage:$nl  $0 5.x.y"
readonly bump_version="$1"

(
    cu::head_line_echo "bump Egon-COLA reactor version to $bump_version"
    cd "$PROJECT_ROOT_DIR"

    mvu::mvn_cmd \
        org.codehaus.mojo:versions-maven-plugin:2.16.2:set \
        -DgenerateBackupPoms=false \
        -DprocessAllModules=true \
        -DnewVersion="$bump_version"
)

(
    cu::head_line_echo "bump README archetype version examples to $bump_version"
    cd "$PROJECT_ROOT_DIR"

    cu::log_then_run -s \
        perl -0pi -e "s~(-DarchetypeVersion=')([^']+)(')~\${1}$bump_version\${3}~g; s~(-DarchetypeVersion=)([0-9][^ \\\\\\n]*)~\${1}$bump_version~g" \
        README.md
)
