#!/bin/bash
set -eEuo pipefail

SELF_PATH=$(realpath -- "$0")
readonly SELF_PATH
SELF_DIR=${SELF_PATH%/*}
readonly SELF_DIR
cd "$SELF_DIR"

BASH_BUDDY_ROOT="$(realpath -- bash-buddy)"
readonly BASH_BUDDY_ROOT
# shellcheck disable=SC1091
source "$BASH_BUDDY_ROOT/lib/trap_error_info.sh"
# shellcheck disable=SC1091
source "$BASH_BUDDY_ROOT/lib/common_utils.sh"
# shellcheck disable=SC1091
source "$BASH_BUDDY_ROOT/lib/java_utils.sh"
# shellcheck disable=SC1091
source "$BASH_BUDDY_ROOT/lib/maven_utils.sh"

PROJECT_ROOT_DIR="$(realpath -- "$SELF_DIR/..")"
readonly PROJECT_ROOT_DIR
export PROJECT_ROOT_DIR

################################################################################
# ci build logic
################################################################################

readonly default_build_jdk_version=21
# shellcheck disable=SC2034
readonly JDK_VERSIONS=(
  "$default_build_jdk_version"
  22
)

# Here use `-Prelease -Dgpg.skip=true` intentionally to check release profile operations without signing.
#
# De-activate a maven profile from command line
#   https://stackoverflow.com/questions/25201430
#
MVU_MVN_OPTS=(
  "${MVU_DEFAULT_MVN_OPTS[@]}"
  -Prelease -Dgpg.skip=true
)
if [ -n "${CI_MORE_MVN_OPTS:-}" ]; then
  # shellcheck disable=SC2206
  MVU_MVN_OPTS+=(${CI_MORE_MVN_OPTS})
fi

################################################################################
# ci build logic
################################################################################

cd "$PROJECT_ROOT_DIR"

extractFirstElementValueFromPom() {
  (($# == 2)) || cu::die "${FUNCNAME[0]} need only 2 arguments, actual arguments: $*"

  local element=$1
  local pom_file=$2
  sed -nE "s~.*<$element>([^<]+)</$element>.*~\1~p" "$pom_file" | head -n 1
}

test_cola_archetype() {
  (
    MVU_MVN_OPTS=("${MVU_DEFAULT_MVN_OPTS[@]}")
    readonly archetype_name=egon-cola-archetype-service

    cu::head_line_echo "test archetype:generate by $archetype_name"

    # NOTE: DO NOT declare archetypeVersion var as readonly, its value is supplied by subshell.
    archetypeVersion=$(extractFirstElementValueFromPom version egon-cola-archetypes/egon-cola-archetype-service/pom.xml)

    # shellcheck disable=SC2030
    readonly demo_dir="egon-cola-archetypes/target/$archetype_name-demo"
    rm -rf "$demo_dir"
    mkdir -p "$demo_dir"
    cd "$demo_dir"

    # shellcheck disable=SC2030
    readonly artifactId=demo-service

    mvu::mvn_cmd archetype:generate \
      -DgroupId=top.egon.demo.archetype-service \
      -DartifactId="$artifactId" \
      -Dversion=1.0.0-SNAPSHOT \
      -Dpackage=top.egon.demo.service \
      -DarchetypeGroupId=top.egon \
      -DarchetypeArtifactId=$archetype_name \
      -DarchetypeVersion="$archetypeVersion" \
      -DinteractiveMode=false \
      -DarchetypeCatalog=local

    cd "$artifactId"
    mvu::mvn_cmd install
  )

  (
    MVU_MVN_OPTS=("${MVU_DEFAULT_MVN_OPTS[@]}")
    readonly archetype_name=egon-cola-archetype-web

    cu::head_line_echo "test archetype:generate by $archetype_name"

    # NOTE: DO NOT declare archetypeVersion var as readonly, its value is supplied by subshell.
    archetypeVersion=$(extractFirstElementValueFromPom version egon-cola-archetypes/egon-cola-archetype-web/pom.xml)

    # shellcheck disable=SC2031
    readonly demo_dir="egon-cola-archetypes/target/$archetype_name-demo"
    rm -rf "$demo_dir"
    mkdir -p "$demo_dir"
    cd "$demo_dir"

    # shellcheck disable=SC2031
    readonly artifactId=demo-web

    mvu::mvn_cmd archetype:generate \
      -DgroupId=top.egon.demo.archetype-web \
      -DartifactId="$artifactId" \
      -Dversion=1.0.0-SNAPSHOT \
      -Dpackage=top.egon.demo.web \
      -DarchetypeGroupId=top.egon \
      -DarchetypeArtifactId=$archetype_name \
      -DarchetypeVersion="$archetypeVersion" \
      -DinteractiveMode=false \
      -DarchetypeCatalog=local

    cd "$artifactId"
    mvu::mvn_cmd install
  )
}

########################################
# default jdk 21, do build and test
########################################

jvu::switch_to_jdk "$default_build_jdk_version"

cu::head_line_echo "build and test with Java $default_build_jdk_version: $JAVA_HOME"

mvu::mvn_cmd clean install

test_cola_archetype

########################################
# test by multiply version jdks
########################################

for jdk_version in "${JDK_VERSIONS[@]}"; do
  # skip default jdk, already tested above
  [ "$jdk_version" = "$default_build_jdk_version" ] && continue

  jvu::switch_to_jdk "$jdk_version"

  cu::head_line_echo "test with Java $jdk_version: $JAVA_HOME"

  # just test without build
  mvu::mvn_cmd surefire:test

  test_cola_archetype
done
