sourceProject=source-projects/egon-cola-source-light
sourceGroupId=top.egon.internal.archetype.source
sourceArtifactId=egon-cola-source-light
sourceVersion=0.1.0-SNAPSHOT
sourcePackage=top.egon.cola.archetype.source.light
targetArtifactId=egon-cola-archetype-light
expectedTopology=root
