<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>top.egon</groupId>
        <artifactId>egon-cola-platforms-parent</artifactId>
        <version>5.3.2</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>egon-cola-platform-dynamic-config-center</artifactId>
    <packaging>pom</packaging>
    <name>egon-cola-platform-dynamic-config-center</name>
    <description>Dynamic configuration center platform for Egon COLA.</description>

    <modules>
        <module>egon-cola-platform-dynamic-config-center-starter</module>
        <module>egon-cola-platform-dynamic-config-center-admin</module>
        <module>egon-cola-platform-dynamic-config-center-test</module>
    </modules>
</project>
