sourceProject=source-projects/egon-cola-source-agent
sourceGroupId=top.egon.internal.archetype.source
sourceArtifactId=egon-cola-source-agent
sourceVersion=0.1.0-SNAPSHOT
sourcePackage=top.egon.cola.archetype.source.agent
targetArtifactId=egon-cola-archetype-agent
expectedTopology=common,domain,application,infrastructure,adapter,starter
