sourceProject=source-projects/egon-cola-source-service
sourceGroupId=top.egon.internal.archetype.source
sourceArtifactId=egon-cola-source-service
sourceVersion=0.1.0-SNAPSHOT
sourcePackage=top.egon.cola.archetype.source.service
targetArtifactId=egon-cola-archetype-service
expectedTopology=common,domain,application,infrastructure,adapter,starter
