spring:
  application:
    name: gateway-test-rpc-consumer
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfigurationV2

server:
  port: 0
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true

egon:
  cola:
    component:
      id:
        enabled: false
      ddc:
        enabled: false
        registry:
          enabled: false
      rpc:
        enabled: false
        consumer:
          enabled: false
          gateway-service-name: egon-gateway-rpc
          gateway-group: default
          gateway-version: 1.0.0
