<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>top.egon</groupId>
        <artifactId>egon-cola-xingyuan-parent</artifactId>
        <version>5.4.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>egon-cola-tianquan-jianshen</artifactId>
    <packaging>pom</packaging>
    <name>egon-cola-tianquan-jianshen</name>
    <description>RBAC3 permission platform for Egon COLA.</description>

    <modules>
        <module>egon-cola-tianquan-jianshen-contract</module>
        <module>egon-cola-tianquan-jianshen-core</module>
        <module>egon-cola-tianquan-jianshen-starter</module>
        <module>egon-cola-tianquan-jianshen-gateway-adapter</module>
        <module>egon-cola-tianquan-jianshen-admin</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>top.egon</groupId>
                <artifactId>egon-cola-tianquan-jianshen-contract</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.egon</groupId>
                <artifactId>egon-cola-tianquan-jianshen-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.egon</groupId>
                <artifactId>egon-cola-tianquan-jianshen-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.egon</groupId>
                <artifactId>egon-cola-tianquan-jianshen-gateway-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>top.egon</groupId>
                <artifactId>egon-cola-tianquan-jianshen-admin</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
