package top.egon.cola.platform.idp.gateway.security;

import java.util.Locale;
import java.util.Set;

/**
 * 声明进入 Gateway 时必须移除的认证头与 IdP 可信身份头。
 * 外部调用者提供的同名身份头不可信，只有验证完成后由映射器重新生成的值才能传给后端服务。
 *
 * <p>Declares the authorization and IdP trusted-identity headers that must be removed at Gateway
 * ingress. Caller-supplied identity headers are untrusted; only values regenerated by the mapper
 * after verification may reach downstream services.</p>
 */
public final class IdpReservedHeaderSanitizer {

    /**
     * 需要在凭据提取阶段移除的标准化请求头集合。
     *
     * <p>Normalized request-header names removed during credential extraction.</p>
     */
    private static final Set<String> RESERVED = Set.of(
            "authorization",
            "x-egon-principal-type",
            "x-egon-identity-sub",
            "x-egon-tenant-id",
            "x-egon-session-id",
            "x-egon-client-id",
            "x-egon-token-id",
            "x-egon-token-version",
            "x-egon-resource-uri",
            "x-egon-resource-version",
            "x-egon-source-biz",
            "x-egon-source-app",
            "x-egon-source-env",
            "x-egon-service-scopes",
            "x-egon-credential-id"
    );

    /**
     * 创建使用固定保留头集合的清理器。
     *
     * <p>Creates a sanitizer backed by the fixed reserved-header set.</p>
     */
    public IdpReservedHeaderSanitizer() {
    }

    /**
     * 返回所有需要从入站请求清除的字段。
     *
     * <p>Returns every field that must be removed from an inbound request.</p>
     *
     * @return 不可变的标准化请求头集合；immutable normalized request-header set
     */
    public Set<String> fieldsToRemove() {
        return RESERVED;
    }

    /**
     * 判断名称是否为由 Gateway 验证后重新生成的可信身份头。
     * Authorization 属于清理范围，但不是下游可信身份头。
     *
     * <p>Determines whether a name denotes a trusted identity header regenerated after Gateway
     * verification. Authorization is removable but is not a downstream trusted-identity header.</p>
     *
     * @param name 待判断的请求头名称；request-header name to inspect
     * @return {@code true} 表示属于可信身份头；{@code true} when it is a trusted identity header
     */
    public boolean trustedIdentityHeader(String name) {
        return name != null
                && RESERVED.contains(name.toLowerCase(Locale.ROOT))
                && !"authorization".equalsIgnoreCase(name);
    }
}
